import mongoose from 'mongoose';

const quizAttemptSchema = new mongoose.Schema(
  {
    quiz: { type: mongoose.Schema.Types.ObjectId, ref: 'Quiz', required: true, index: true },
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    course: { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true, index: true },
    answers: { type: Map, of: Number, default: {} },
    score: { type: Number, default: 0 },
    total: { type: Number, default: 0 },
    percent: { type: Number, default: 0 },
    detail: { type: Array, default: [] },
    // Set on the device when the student actually answered, which can be
    // hours before the attempt reaches the server.
    takenAt: { type: Date, required: true },
    syncedAt: { type: Date, default: Date.now },
    takenOffline: { type: Boolean, default: false },
    // Idempotency key generated by the client so a retried sync cannot
    // create a duplicate attempt.
    clientOpId: { type: String, required: true },
    // Set once the result hash is anchored on the ledger.
    ledgerTxId: { type: String, default: '' },
  },
  { timestamps: true }
);

quizAttemptSchema.index({ clientOpId: 1, student: 1 }, { unique: true });

export default mongoose.model('QuizAttempt', quizAttemptSchema);
